kind: Pod
apiVersion: v1beta1
id: &name keystone-db-sync
labels:
  name: *name
desiredState:
  manifest:
    version: v1beta1
    containers:
      - name: *name
        registry: %docker_registry%
        image: %docker_image_prefix%/keystone:latest
        env:
          - key: ADMIN_TOKEN
            value: %keystone_admin_token%
          - key: DB_URI
            value: %keystone_db_uri%
          - key: RABBITMQ_PASSWORD
            value: %rabbitmq_password%
          - key: ADMIN_PASSWORD
            value: %keystone_admin_password%
        command: ["keystone-manage", "db_sync"]
    restartPolicy:
      onFailure: {}
