kind: Pod
apiVersion: v1beta1
id: &name neutron-db-sync
labels:
  name: *name
desiredState:
  manifest:
    version: v1beta1
    containers:
      - name: *name
        registry: %docker_registry%
        image: %docker_image_prefix%/neutron:latest
        env:
          - key: DB_URI
            value: %neutron_db_uri%
          - key: ADMIN_PASSWORD
            value: %neutron_admin_password%
        command: ["neutron-db-manage", "--config-file=/home/user/etc/neutron/neutron.conf", "--config-file=/home/user/etc/neutron/ml2_conf.ini", "upgrade", "head"]
    restartPolicy:
      onFailure: {}
