kind: ReplicationController
apiVersion: v1beta1
id: &name nova-api
labels:
  name: *name
desiredState:
  replicas: 3
  replicaSelector:
    name: *name
  podTemplate:
    labels:
      name: *name
    desiredState:
      manifest:
        version: v1beta1
        containers:
          - name: *name
            registry: %docker_registry%
            image: %docker_image_prefix%/nova:latest
            ports:
              - name: osapi
                containerPort: 8774
              - name: ec2
                containerPort: 8773
              - name: metadata
                containerPort: 8775
            env:
              - key: DB_URI
                value: %nova_db_uri%
              - key: RABBITMQ_PASSWORD
                value: %rabbitmq_password%
              - key: ADMIN_PASSWORD
                value: %nova_admin_password%
              - key: NEUTRON_METADATA_SECRET
                value: %neutron_metadata_secret%
              - key: NEUTRON_ADMIN_PASSWORD
                value: %neutron_admin_password%
            command: ["nova-api", "--config-file=/home/user/etc/nova/nova.conf"]
            # livenessProbe?
